baseURL = "https://dqianyu.github.io/qd33/"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "home"

relativeURLs = false
buildFuture = true
canonifyURLs = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "publications"
url = "/publication/"
weight = 2

[[menu.main]]
name = "research"
url = "/research/"
weight = 3

[[menu.main]]
name = "teaching"
url = "/teaching/"
weight = 4


[params]
custom_css = ["css/theme-override.css"]
description = "A simple, minimal blog for those who love text."
footer = '''
<a href="https://scholar.google.com/citations?user=vhdn5qAAAAAJ" target="_blank" rel="noopener noreferrer">
  Google Scholar</a> ·
<a href="https://github.com/dqianyu" target="_blank">GitHub</a> ·
<a href="https://www.linkedin.com/in/qy42" target="_blank">LinkedIn</a>
'''
